### ISSUE TITLE
Hardcoded Plugin path in Docs deployment

### ISSUE THREAD

**Issue by stoeps13** [HCL-TECH-SOFTWARE/connections-automation#337]
You can change the Plugin install directory with `plg_install_location`, but the propagate task in docs does use hardcoded path:

https://github.com/HCL-TECH-SOFTWARE/connections-automation/blob/d135841f579833b946b0ac8bd5fbfaf6eaf64cad/roles/hcl/docs/tasks/propagate_plugin.yml#L9-L12

This should be changed to something like

```yml
- name:                 "Copy the files to {{ __plg_install_location }}/config/"
  copy:
    src:                "/tmp/wct_generated_plugins_docs_{{ inventory_hostname_short }}/plugin-cfg.xml"
    dest:               "{{ __plg_install_location }}/config/{{ inventory_hostname_short }}/plugin-cfg.xml"
    remote_src:         yes
```
Additionally the vars/main.yml needs a new entry for 

```yml
__plg_install_location: "{{ plg_install_location | default('/opt/IBM/WebSphere/Plugins') }}"
```
